development:
#   adapter: postgresql
#   database: pcol_dev
#   host: localhost
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
#   adapter: postgresql
#   database: pcol_test
  pool: 5
  timeout: 5000
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: pcol_prod
  pool: 5
  timeout: 5000